name: CI - Fenty Beauty App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      RESEND_API_KEY: re_6v4kzH6h_5kkNLLk6YbCCTRVftd4R6e5m
      DATABASE_URL: postgresql://postgres:password@localhost:5432/capstone_db?schema=public
      NEXTAUTH_SECRET: your-secret-key-here-generate-with-openssl-rand-base64-32
      NEXTAUTH_URL: http://localhost:3000

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build